Roll back the -checks test build to 18.04
20.04 intermittently causes build failures as LeakSanitizer noisily errors on failure to attach to threads. It assumes that this is due to a lack of permissions, when in fact it seems to be simply a race with the thread completing and exiting quickly.

This has been visible as the following test failure:

	Error: test_postgresql_complains_if_there_are_tables_in_other_schemas_not_in_the_search_path(SchemaToMultipleDatabaseSchemasTest): RuntimeError: Unexpected stderr output: "The search_path is currently set to public,private_schema but there are also tables in private_schemax. Either add to the 'to' end search_path using --set-to-variables or restrict the 'from' end search_path using --set-from-variables.\n==232==LeakSanitizer has encountered a fatal error.\n==232==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1\n==232==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)"; should be "The search_path is currently set to public,private_schema but there are also tables in private_schemax. Either add to the 'to' end search_path using --set-to-variables or restrict the 'from' end search_path using --set-from-variables."